// Template all webpages share

import "./globals.css";

// Fonts
// Fairly straightforward create lowercase variable to hold value 
// to then be served in className
import { EB_Garamond } from 'next/font/google'

// Components
// When doing components theres a space then /> as in <Component />
import GradientHeader from './components/GradientHeader'

import RadioPlayer from './components/RadioPlayer'

const eb_garamond = EB_Garamond({ subsets: ['latin' ]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className = {eb_garamond.className}>
        <GradientHeader />
        <RadioPlayer />
        {children}
      </body>
    </html>
  );
}
